/**
 * Complete mapping of BitShares operation type numbers to human-readable names.
 * Source: bitshares-core/libraries/protocol/include/graphene/protocol/operations.hpp
 */
export const OP_NAMES: Record<number, string> = {
  0: "Transfer",
  1: "Limit Order Create",
  2: "Limit Order Cancel",
  3: "Call Order Update",
  4: "Fill Order",
  5: "Account Create",
  6: "Account Update",
  7: "Account Whitelist",
  8: "Account Upgrade",
  9: "Account Transfer",
  10: "Asset Create",
  11: "Asset Update",
  12: "Asset Update Bitasset",
  13: "Asset Update Feed Producers",
  14: "Asset Issue",
  15: "Asset Reserve",
  16: "Asset Fund Fee Pool",
  17: "Asset Settle",
  18: "Asset Global Settle",
  19: "Asset Publish Feed",
  20: "Witness Create",
  21: "Witness Update",
  22: "Proposal Create",
  23: "Proposal Update",
  24: "Proposal Delete",
  25: "Withdraw Permission Create",
  26: "Withdraw Permission Update",
  27: "Withdraw Permission Claim",
  28: "Withdraw Permission Delete",
  29: "Committee Member Create",
  30: "Committee Member Update",
  31: "Committee Member Update Global Parameters",
  32: "Vesting Balance Create",
  33: "Vesting Balance Withdraw",
  34: "Worker Create",
  35: "Custom",
  36: "Assert",
  37: "Balance Claim",
  38: "Override Transfer",
  39: "Transfer to Blind",
  40: "Blind Transfer",
  41: "Transfer from Blind",
  42: "Asset Settle Cancel",
  43: "Asset Claim Fees",
  44: "FBA Distribute",
  45: "Bid Collateral",
  46: "Execute Bid",
  47: "Asset Claim Pool",
  48: "Asset Update Issuer",
  49: "HTLC Create",
  50: "HTLC Redeem",
  51: "HTLC Redeemed",
  52: "HTLC Extend",
  53: "HTLC Refund",
  54: "Custom Authority Create",
  55: "Custom Authority Update",
  56: "Custom Authority Delete",
  57: "Ticket Create",
  58: "Ticket Update",
  59: "Liquidity Pool Create",
  60: "Liquidity Pool Delete",
  61: "Liquidity Pool Deposit",
  62: "Liquidity Pool Withdraw",
  63: "Liquidity Pool Exchange",
  64: "SameT Fund Create",
  65: "SameT Fund Delete",
  66: "SameT Fund Update",
  67: "SameT Fund Borrow",
  68: "SameT Fund Repay",
  69: "Credit Offer Create",
  70: "Credit Offer Delete",
  71: "Credit Offer Update",
  72: "Credit Offer Accept",
  73: "Credit Deal Repay",
  74: "Credit Deal Expired",
  75: "Liquidity Pool Update",
  76: "Credit Deal Update",
  77: "Limit Order Update",
};
